# Number of labels to fetch (optional). Defaults to 100
# numLabels: 40
# These labels will not be used even if the issue contains them (optional).
# Pass a blank array if no labels are to be excluded.
# excludeLabels: []
excludeLabels: []
# custom configuration to override default behaviour
# control explicitly what gets added and when
custom:
  - location: title
    keywords:
      - 'bug:'
    labels:
      - ':beetle: bug'

  - location: title
    keywords:
      - 'anon'
      - 'apex'
    labels:
      - ANON-APEX

  - location: title
    keywords:
      - 'automation'
    labels:
      - AUTOMATION

  - location: title
    keywords:
      - 'deploy'
    labels:
      - DEPLOY

  - location: title
    keywords:
      - 'docs'
    labels:
      - DOCS

  - location: title
    keywords:
      - 'backend'
    labels:
      - BACKEND

  - location: title
    keywords:
      - 'landing'
    labels:
      - LANDING

  - location: title
    keywords:
      - 'load'
    labels:
      - LOAD

  - location: title
    keywords:
      - 'permission'
    labels:
      - PERMISSIONS

  - location: title
    keywords:
      - 'query'
    labels:
      - QUERY

  - location: title
    keywords:
      - 'api'
    labels:
      - SFDC-API
