version: '3.8'
services:
  jetstream:
    image: jetstream
    depends_on:
      - db
    environment:
      NODE_ENV: production
      ENVIRONMENT: production
      JESTREAM_POSTGRES_DBURI: postgres://postgres:postgres@postgres:5432/postgres
      JESTREAM_SESSION_SECRET: 8e52194ce3b6650b93e95a5c40a705b2
      JETSTREAM_CLIENT_URL: http://localhost:3333/app
      JETSTREAM_SERVER_DOMAIN: localhost:3333
      JETSTREAM_SERVER_URL: http://localhost:3333
      AUTH0_DOMAIN: '${AUTH0_DOMAIN}'
      AUTH0_M2M_DOMAIN: '${AUTH0_M2M_DOMAIN}'
      AUTH0_CLIENT_ID: '${AUTH0_CLIENT_ID}'
      AUTH0_MGMT_CLIENT_ID: '${AUTH0_MGMT_CLIENT_ID}'
      AUTH0_MGMT_CLIENT_SECRET: '${AUTH0_MGMT_CLIENT_SECRET}'
      AUTH0_CLIENT_SECRET: '${AUTH0_CLIENT_SECRET}'
      AUTH_AUDIENCE: '${AUTH_AUDIENCE}'
      SFDC_FALLBACK_API_VERSION: '${SFDC_FALLBACK_API_VERSION}'
      SFDC_CONSUMER_SECRET: '${SFDC_CONSUMER_SECRET}'
      SFDC_CONSUMER_KEY: '${SFDC_CONSUMER_KEY}'
      SFDC_CALLBACK_URL: '${SFDC_CALLBACK_URL}'
      NX_AG_GRID_KEY: '${NX_AG_GRID_KEY}'
      NX_ROLLBAR_KEY: '${NX_ROLLBAR_KEY}'
      NX_AMPLITUDE_KEY: '${NX_AMPLITUDE_KEY}'
      NX_AUTH_AUDIENCE: '${NX_AUTH_AUDIENCE}'
    ports:
      - '3333:3333'
      - '9229:9229'
    links:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
