name: CI
# TODO: figure out specifics of when this should run
on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  CONTENTFUL_HOST: cdn.contentful.com
  CONTENTFUL_SPACE: wuv9tl5d77ll
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
  NX_AUTH_AUDIENCE: http://getjetstream.app/app_metadata
  NX_AG_GRID_KEY: ${{ secrets.NX_AG_GRID_KEY }}
  NX_ROLLBAR_KEY: ${{ secrets.NX_ROLLBAR_KEY }}
  NX_AMPLITUDE_KEY: ${{ secrets.NX_AMPLITUDE_KEY }}
  JESTREAM_SESSION_SECRET: ${{ secrets.JESTREAM_SESSION_SECRET }}
  JETSTREAM_CLIENT_URL: http://localhost:4200/app
  JETSTREAM_SERVER_DOMAIN: localhost:3333
  JETSTREAM_SERVER_URL: http://localhost:3333
  JESTREAM_POSTGRES_DBURI: postgres://postgres:postgres@postgres:5432/postgres
  EXAMPLE_USER_OVERRIDE: true
  SFDC_CALLBACK_URL: http://localhost:3333/oauth/sfdc/callback
  SFDC_CONSUMER_KEY: ${{ secrets.SFDC_CONSUMER_KEY }}
  SFDC_CONSUMER_SECRET: ${{ secrets.SFDC_CONSUMER_SECRET }}
  SFDC_ENC_KEY: ${{ secrets.SFDC_ENC_KEY }}
  SFDC_FALLBACK_API_VERSION: '56.0'
  TEST_E2E_LOGIN_USERNAME: 'integration@jetstream.app.e2e'
  TEST_E2E_LOGIN_PASSWORD: 'TQC8vgu_fdx@qzu2tng'
  TEST_E2E_LOGIN_URL: 'https://jetstream-e2e-dev-ed.develop.my.salesforce.com'
  GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  build-and-test: # This ensures that the build is cached for more reliable deploy on render
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    # Create a postgres service
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Init NX CI run
        run: npx nx-cloud start-ci-run
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Start NX CI run
        run: npx nx affected --target=build --parallel --max-parallel=2 --configuration=production
      - name: Generate and seed DB
        run: yarn db:generate && yarn db:seed
      - name: Run E2E tests
        run: yarn playwright:test
      - name: Upload test results
        if: always() # This ensures step will always run even if prior steps fail
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      - name: Stop CI agents
        if: always() # This ensures step will always run even if prior steps fail
        run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
