name: CI
# TODO: figure out specifics of when this should run
on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  CONTENTFUL_HOST: cdn.contentful.com
  CONTENTFUL_SPACE: wuv9tl5d77ll
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
  NX_AUTH_AUDIENCE: http://getjetstream.app/app_metadata
  NX_AG_GRID_KEY: ${{ secrets.NX_AG_GRID_KEY }}
  NX_ROLLBAR_KEY: ${{ secrets.NX_ROLLBAR_KEY }}
  NX_AMPLITUDE_KEY: ${{ secrets.NX_AMPLITUDE_KEY }}
jobs:
  build-app-with-nx-cache: # This ensures that the build is cached for more reliable deploy on render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Init NX CI run
        run: npx nx-cloud start-ci-run
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Start NX CI run
        run: npx nx affected --target=build --parallel --max-parallel=2 --configuration=production
      - name: Run E2E tests
        run: yarn playwright:test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      - name: Stop CI agents
        run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
