name: Create Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3
      - name: Init npm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Init git user
        run: |
          git config --global user.email "paustint@gmail.com"
          git config --global user.name "Release Workflow"
      - name: Run Release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
